name: Trigger auto deployment for php-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/php-prod-AutoDeployTrigger-02771d92-1e9b-479b-92c4-448a2b603e69.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jagorddemo.azurecr.io
          username: ${{ secrets.PHPPROD_REGISTRY_USERNAME }}
          password: ${{ secrets.PHPPROD_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jagorddemo.azurecr.io/php-prod:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PHPPROD_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n php-prod -g jagorddemo --server jagorddemo.azurecr.io --username  ${{ secrets.PHPPROD_REGISTRY_USERNAME }} --password ${{ secrets.PHPPROD_REGISTRY_PASSWORD }}
            az containerapp update -n php-prod -g jagorddemo --image jagorddemo.azurecr.io/php-prod:${{ github.sha }}
